# Continuos integration with SonarQube
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sonarcloud:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Scanning code with SonarCloud to detect bugs, vulnerabilities and code smells.

      # Runs a set of commands using the runners shell
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
          # Set the sonar.projectBaseDir analysis property
          projectBaseDir: ./src
          # Additional arguments to the sonarcloud scanner
          args: >
            -Dsonar.organization=drodriguez-dev
            -Dsonar.projectKey=drodriguez-dev_tour-of-heroes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
